--ELIMINAR COLUMNA NUM_SEGURO
ALTER TABLE pacientes
DROP COLUMN num_seguro;

--ACTUALIZAR TIPO DE DATO DE BIGSERIAL A VARCHAR
-- PRIMERO ELIMINAR RESTRICCIONES, OSEA LA LLAVE PRIMARIA
ALTER TABLE pacientes DROP CONSTRAINT pacientes_pkey;
--CAMBIAR EL TIPO DE DATO
ALTER TABLE pacientes ALTER COLUMN id_paciente SET DATA TYPE VARCHAR(15);
--VOLVER A AÑADIR LA LLAVE PRIMARIA
ALTER TABLE pacientes ADD PRIMARY KEY (id_paciente);



